# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: build
    pool:
      name: Hosted Windows 2019 with VS2019
      demands: azureps

    steps:

      - task: CmdLine@2
        inputs:
          script: 'choco install winrar' 

      #- task: PublishBuildArtifacts@1
      #  displayName: 'Publish Functional Tests'
      #  inputs:
      #    PathtoPublish: 'FunctionalTests/SampleApplication.FunctionalTests/'
      #    ArtifactName: 'FunctionalTests'
      #    publishLocation: 'Container'
#      - task: DotNetCoreCLI@2
#        displayName: 'Package'
#        inputs:
#          command: publish
#          publishWebProjects: True
#          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#          zipAfterPublish: True
#- stage : package
#  displayName: 'Package'
#  dependsOn: build
#  condition: succeeded()