# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: build
    pool:
      name: Hosted Windows 2019 with VS2019
      demands: azureps

    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Tests'
        inputs:
          command: test
          projects: 'SampleApplication\SampleApplication.Tests\SampleApplication.Tests.csproj'
          arguments: '--configuration $(buildConfiguration) --collect "XPlat Code coverage"'

      - task: DotNetCoreCLI@2
        inputs:
            command: custom
            custom: tool
            arguments: install --tool-path . dotnet-reportgenerator-globaltool
        displayName: Install ReportGenerator tool
  
      - script: reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
        displayName: Create reports
  
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml 
          
      - task: AzurePowerShell@3
        displayName: 'Validate ARM template'
        inputs:
          azureSubscription: 'pipelineconnectionname'
          ScriptPath: 'SampleApplication/SampleApplication.ResourceGroup/Deploy-AzureResourceGroup.ps1'
          ScriptArguments: -ResourceGroupName 'vladtestpipeline' -ResourceGroupLocation 'centralus' -StorageAccountName '' -TemplateFile 'azuredeploy.json' -TemplateParametersFile 'devenvdeploy.parameters.json' -ArtifactStagingDirectory '.' -DSCSourceFolder '.\DSC' -ValidateOnly
          azurePowerShellVersion: LatestVersion
      
      - task: DotNetCoreCLI@2
        displayName: 'Package'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact: drop'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish ARM: drop'
        inputs:
          PathtoPublish: 'SampleApplication/SampleApplication.ResourceGroup/'
          ArtifactName: 'drop'
          publishLocation: 'Container'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Functional Tests'
        inputs:
          PathtoPublish: 'SampleApplication/SampleApplication.FunctionalTests/bin/$(buildConfiguration)/netcoreapp2.1/publish/'
          ArtifactName: 'FunctionalTests'
          publishLocation: 'Container'
#      - task: DotNetCoreCLI@2
#        displayName: 'Package'
#        inputs:
#          command: publish
#          publishWebProjects: True
#          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#          zipAfterPublish: True
#- stage : package
#  displayName: 'Package'
#  dependsOn: build
#  condition: succeeded()